# Generated by Django 5.0.2 on 2024-02-27 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subemail',
            name='frequency',
            field=models.CharField(choices=[('weekly', 'weekly'), ('monthly', 'monthly')], default='weekly', max_length=10),
        ),
    ]
